### ISSUE TITLE
No error or connection: ERR_NGROK_3200

### ISSUE THREAD

**Issue by JCzz** [ngrok/kubernetes-ingress-controller#247] opened 2023-06-09 10:11 UTC
### What happened

Great idea with an ingress controller!

Following this introduction: https://ngrok.com/blog-post/ngrok-k8s

I am able to install and I got this running:
```
kubectl get ingress
NAME        CLASS   HOSTS             ADDRESS   PORTS   AGE
game-2048   ngrok   awear.ngrok.app             80      94m
```

kubectl get pods
```
NAME                                                              READY   STATUS    RESTARTS   AGE
game-2048-c4b479d49-zt5xw                                         1/1     Running   0          102m
ngrok-ingress-controller-kubernetes-ingress-controller-mandrwcn   1/1     Running   0          50m

```
I am running on a KinD cluster on MacOS latest:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
```

kubectl get svc
```
NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
game-2048                        ClusterIP   10.96.172.131   <none>        80/TCP      118m
```

I have tried:
https://awear.ngrok.app
https://awear.ngrok-free.app
https://awear.ngrok-free.dev

I get:
```
ERR_NGROK_3200
Tunnel awear.ngrok.app not found
```

I also tried:
`kubectl edit ingress game-2048`
and changed "- host: awear.ngrok.app" to "- host: awear.ngrok-free.app"
But still the same error: ERR_NGROK_3200

Any ideas?

Thanks

### What you think should happen instead

Be able to access the ingress, routing to the serving the service

**Comment by nikolay-ngrok** [comment] 2023-06-09 13:36
👋  @JCzz 

I would suggest getting the logs (`kubectl logs` of the pod/replicaset) for the ingress controller, to see what is going on. Potentially you could attach them here. Alternatively, you could also `kubectl get events` to see if everything is fine.

If I had to guess, it sounds like one of your secrets (`API_KEY` or `AUTHTOKEN`) is not configured properly. You could run something like `kubectl describe secrets ngrok-ingress-controller-kubernetes-ingress-controller-credentials` to see what you've got (both should be present, showing `49 bytes`), and even decode them to see if they match what you've got from the dashboard.

**Comment by nikolay-ngrok** [comment] 2023-06-14 12:54
@JCzz from what I can see, the controller cannot talk the the k8s api server. Haven't had the time to investigate why this could be the case just yet, but letting you know just in case you've got some ideas.

**Comment by nikolay-ngrok** [comment] 2023-09-13 15:18
Hello @JCzz , just following up here - were you able to resolve your issue?

**Comment by alex-bezek** [comment] 2024-03-04 17:55
Closing as we can't reproduce and the message seems clear it was a connection problem to the k8s api server. Let us know if you still encounter this issue.

**Closed by alex-bezek** 2024-03-04 17:55 UTC
Labels: bug, area/controller, needs-triage
